#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 09 03:31:31 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=superDuperVanilla.zip
enableShaders=false
